// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Configuration.proto

package org.example.protos;

public final class ConfigurationOuterClass {
  private ConfigurationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.protos.Configuration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Hata tolerans seviyesi
     * </pre>
     *
     * <code>int32 fault_tolerance_level = 1;</code>
     * @return The faultToleranceLevel.
     */
    int getFaultToleranceLevel();

    /**
     * <code>.org.example.protos.Configuration.Method method = 2;</code>
     * @return The enum numeric value on the wire for method.
     */
    int getMethodValue();
    /**
     * <code>.org.example.protos.Configuration.Method method = 2;</code>
     * @return The method.
     */
    Configuration.Method getMethod();
  }
  /**
   * Protobuf type {@code org.example.protos.Configuration}
   */
  public static final class Configuration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.protos.Configuration)
      ConfigurationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Configuration.newBuilder() to construct.
    private Configuration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Configuration() {
      method_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Configuration();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConfigurationOuterClass.internal_static_org_example_protos_Configuration_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConfigurationOuterClass.internal_static_org_example_protos_Configuration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Configuration.class, Builder.class);
    }

    /**
     * Protobuf enum {@code org.example.protos.Configuration.Method}
     */
    public enum Method
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Başlatma komutu
       * </pre>
       *
       * <code>STRT = 0;</code>
       */
      STRT(0),
      /**
       * <pre>
       * Durdurma komutu
       * </pre>
       *
       * <code>STOP = 1;</code>
       */
      STOP(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * Başlatma komutu
       * </pre>
       *
       * <code>STRT = 0;</code>
       */
      public static final int STRT_VALUE = 0;
      /**
       * <pre>
       * Durdurma komutu
       * </pre>
       *
       * <code>STOP = 1;</code>
       */
      public static final int STOP_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Method valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Method forNumber(int value) {
        switch (value) {
          case 0: return STRT;
          case 1: return STOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Method>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Method> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Method>() {
              public Method findValueByNumber(int number) {
                return Method.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Configuration.getDescriptor().getEnumTypes().get(0);
      }

      private static final Method[] VALUES = values();

      public static Method valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Method(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.example.protos.Configuration.Method)
    }

    public static final int FAULT_TOLERANCE_LEVEL_FIELD_NUMBER = 1;
    private int faultToleranceLevel_;
    /**
     * <pre>
     * Hata tolerans seviyesi
     * </pre>
     *
     * <code>int32 fault_tolerance_level = 1;</code>
     * @return The faultToleranceLevel.
     */
    @Override
    public int getFaultToleranceLevel() {
      return faultToleranceLevel_;
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private int method_;
    /**
     * <code>.org.example.protos.Configuration.Method method = 2;</code>
     * @return The enum numeric value on the wire for method.
     */
    @Override public int getMethodValue() {
      return method_;
    }
    /**
     * <code>.org.example.protos.Configuration.Method method = 2;</code>
     * @return The method.
     */
    @Override public Method getMethod() {
      @SuppressWarnings("deprecation")
      Method result = Method.valueOf(method_);
      return result == null ? Method.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (faultToleranceLevel_ != 0) {
        output.writeInt32(1, faultToleranceLevel_);
      }
      if (method_ != Method.STRT.getNumber()) {
        output.writeEnum(2, method_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (faultToleranceLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, faultToleranceLevel_);
      }
      if (method_ != Method.STRT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, method_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Configuration)) {
        return super.equals(obj);
      }
      Configuration other = (Configuration) obj;

      if (getFaultToleranceLevel()
          != other.getFaultToleranceLevel()) return false;
      if (method_ != other.method_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FAULT_TOLERANCE_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getFaultToleranceLevel();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + method_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Configuration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Configuration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Configuration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Configuration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Configuration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Configuration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Configuration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Configuration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Configuration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Configuration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Configuration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Configuration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Configuration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.protos.Configuration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.protos.Configuration)
        ConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ConfigurationOuterClass.internal_static_org_example_protos_Configuration_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ConfigurationOuterClass.internal_static_org_example_protos_Configuration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Configuration.class, Builder.class);
      }

      // Construct using org.example.protos.ConfigurationOuterClass.Configuration.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        faultToleranceLevel_ = 0;

        method_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ConfigurationOuterClass.internal_static_org_example_protos_Configuration_descriptor;
      }

      @Override
      public Configuration getDefaultInstanceForType() {
        return Configuration.getDefaultInstance();
      }

      @Override
      public Configuration build() {
        Configuration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Configuration buildPartial() {
        Configuration result = new Configuration(this);
        result.faultToleranceLevel_ = faultToleranceLevel_;
        result.method_ = method_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Configuration) {
          return mergeFrom((Configuration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Configuration other) {
        if (other == Configuration.getDefaultInstance()) return this;
        if (other.getFaultToleranceLevel() != 0) {
          setFaultToleranceLevel(other.getFaultToleranceLevel());
        }
        if (other.method_ != 0) {
          setMethodValue(other.getMethodValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                faultToleranceLevel_ = input.readInt32();

                break;
              } // case 8
              case 16: {
                method_ = input.readEnum();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int faultToleranceLevel_ ;
      /**
       * <pre>
       * Hata tolerans seviyesi
       * </pre>
       *
       * <code>int32 fault_tolerance_level = 1;</code>
       * @return The faultToleranceLevel.
       */
      @Override
      public int getFaultToleranceLevel() {
        return faultToleranceLevel_;
      }
      /**
       * <pre>
       * Hata tolerans seviyesi
       * </pre>
       *
       * <code>int32 fault_tolerance_level = 1;</code>
       * @param value The faultToleranceLevel to set.
       * @return This builder for chaining.
       */
      public Builder setFaultToleranceLevel(int value) {
        
        faultToleranceLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Hata tolerans seviyesi
       * </pre>
       *
       * <code>int32 fault_tolerance_level = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFaultToleranceLevel() {
        
        faultToleranceLevel_ = 0;
        onChanged();
        return this;
      }

      private int method_ = 0;
      /**
       * <code>.org.example.protos.Configuration.Method method = 2;</code>
       * @return The enum numeric value on the wire for method.
       */
      @Override public int getMethodValue() {
        return method_;
      }
      /**
       * <code>.org.example.protos.Configuration.Method method = 2;</code>
       * @param value The enum numeric value on the wire for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodValue(int value) {
        
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.protos.Configuration.Method method = 2;</code>
       * @return The method.
       */
      @Override
      public Method getMethod() {
        @SuppressWarnings("deprecation")
        Method result = Method.valueOf(method_);
        return result == null ? Method.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.example.protos.Configuration.Method method = 2;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(Method value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        method_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.protos.Configuration.Method method = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        
        method_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.protos.Configuration)
    }

    // @@protoc_insertion_point(class_scope:org.example.protos.Configuration)
    private static final Configuration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Configuration();
    }

    public static Configuration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Configuration>
        PARSER = new com.google.protobuf.AbstractParser<Configuration>() {
      @Override
      public Configuration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Configuration> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Configuration> getParserForType() {
      return PARSER;
    }

    @Override
    public Configuration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protos_Configuration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protos_Configuration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023Configuration.proto\022\022org.example.proto" +
      "s\"\206\001\n\rConfiguration\022\035\n\025fault_tolerance_l" +
      "evel\030\001 \001(\005\0228\n\006method\030\002 \001(\0162(.org.example" +
      ".protos.Configuration.Method\"\034\n\006Method\022\010" +
      "\n\004STRT\020\000\022\010\n\004STOP\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_protos_Configuration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_protos_Configuration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protos_Configuration_descriptor,
        new String[] { "FaultToleranceLevel", "Method", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
