// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.example.protos;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.protos.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.example.protos.Message.Demand demand = 1;</code>
     * @return The enum numeric value on the wire for demand.
     */
    int getDemandValue();
    /**
     * <code>.org.example.protos.Message.Demand demand = 1;</code>
     * @return The demand.
     */
    Message.Demand getDemand();

    /**
     * <code>.org.example.protos.Message.Response response = 2;</code>
     * @return The enum numeric value on the wire for response.
     */
    int getResponseValue();
    /**
     * <code>.org.example.protos.Message.Response response = 2;</code>
     * @return The response.
     */
    Message.Response getResponse();
  }
  /**
   * Protobuf type {@code org.example.protos.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.protos.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      demand_ = 0;
      response_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageOuterClass.internal_static_org_example_protos_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageOuterClass.internal_static_org_example_protos_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    /**
     * Protobuf enum {@code org.example.protos.Message.Demand}
     */
    public enum Demand
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Capacity talebi
       * </pre>
       *
       * <code>CPCTY = 0;</code>
       */
      CPCTY(0),
      /**
       * <pre>
       * Başlatma komutu
       * </pre>
       *
       * <code>STRT = 1;</code>
       */
      STRT(1),
      /**
       * <pre>
       * Durdurma komutu
       * </pre>
       *
       * <code>STOP = 2;</code>
       */
      STOP(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * Capacity talebi
       * </pre>
       *
       * <code>CPCTY = 0;</code>
       */
      public static final int CPCTY_VALUE = 0;
      /**
       * <pre>
       * Başlatma komutu
       * </pre>
       *
       * <code>STRT = 1;</code>
       */
      public static final int STRT_VALUE = 1;
      /**
       * <pre>
       * Durdurma komutu
       * </pre>
       *
       * <code>STOP = 2;</code>
       */
      public static final int STOP_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Demand valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Demand forNumber(int value) {
        switch (value) {
          case 0: return CPCTY;
          case 1: return STRT;
          case 2: return STOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Demand>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Demand> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Demand>() {
              public Demand findValueByNumber(int number) {
                return Demand.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Demand[] VALUES = values();

      public static Demand valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Demand(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.example.protos.Message.Demand)
    }

    /**
     * Protobuf enum {@code org.example.protos.Message.Response}
     */
    public enum Response
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Başarılı yanıt
       * </pre>
       *
       * <code>YEP = 0;</code>
       */
      YEP(0),
      /**
       * <pre>
       * Başarısız yanıt
       * </pre>
       *
       * <code>NOP = 1;</code>
       */
      NOP(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * Başarılı yanıt
       * </pre>
       *
       * <code>YEP = 0;</code>
       */
      public static final int YEP_VALUE = 0;
      /**
       * <pre>
       * Başarısız yanıt
       * </pre>
       *
       * <code>NOP = 1;</code>
       */
      public static final int NOP_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Response valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Response forNumber(int value) {
        switch (value) {
          case 0: return YEP;
          case 1: return NOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Response>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Response> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Response>() {
              public Response findValueByNumber(int number) {
                return Response.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.getDescriptor().getEnumTypes().get(1);
      }

      private static final Response[] VALUES = values();

      public static Response valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Response(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.example.protos.Message.Response)
    }

    public static final int DEMAND_FIELD_NUMBER = 1;
    private int demand_;
    /**
     * <code>.org.example.protos.Message.Demand demand = 1;</code>
     * @return The enum numeric value on the wire for demand.
     */
    @Override public int getDemandValue() {
      return demand_;
    }
    /**
     * <code>.org.example.protos.Message.Demand demand = 1;</code>
     * @return The demand.
     */
    @Override public Demand getDemand() {
      @SuppressWarnings("deprecation")
      Demand result = Demand.valueOf(demand_);
      return result == null ? Demand.UNRECOGNIZED : result;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private int response_;
    /**
     * <code>.org.example.protos.Message.Response response = 2;</code>
     * @return The enum numeric value on the wire for response.
     */
    @Override public int getResponseValue() {
      return response_;
    }
    /**
     * <code>.org.example.protos.Message.Response response = 2;</code>
     * @return The response.
     */
    @Override public Response getResponse() {
      @SuppressWarnings("deprecation")
      Response result = Response.valueOf(response_);
      return result == null ? Response.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (demand_ != Demand.CPCTY.getNumber()) {
        output.writeEnum(1, demand_);
      }
      if (response_ != Response.YEP.getNumber()) {
        output.writeEnum(2, response_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (demand_ != Demand.CPCTY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, demand_);
      }
      if (response_ != Response.YEP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      if (demand_ != other.demand_) return false;
      if (response_ != other.response_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEMAND_FIELD_NUMBER;
      hash = (53 * hash) + demand_;
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + response_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.protos.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.protos.Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageOuterClass.internal_static_org_example_protos_Message_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageOuterClass.internal_static_org_example_protos_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using org.example.protos.MessageOuterClass.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        demand_ = 0;

        response_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageOuterClass.internal_static_org_example_protos_Message_descriptor;
      }

      @Override
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      @Override
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Message buildPartial() {
        Message result = new Message(this);
        result.demand_ = demand_;
        result.response_ = response_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.demand_ != 0) {
          setDemandValue(other.getDemandValue());
        }
        if (other.response_ != 0) {
          setResponseValue(other.getResponseValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                demand_ = input.readEnum();

                break;
              } // case 8
              case 16: {
                response_ = input.readEnum();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int demand_ = 0;
      /**
       * <code>.org.example.protos.Message.Demand demand = 1;</code>
       * @return The enum numeric value on the wire for demand.
       */
      @Override public int getDemandValue() {
        return demand_;
      }
      /**
       * <code>.org.example.protos.Message.Demand demand = 1;</code>
       * @param value The enum numeric value on the wire for demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemandValue(int value) {
        
        demand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.protos.Message.Demand demand = 1;</code>
       * @return The demand.
       */
      @Override
      public Demand getDemand() {
        @SuppressWarnings("deprecation")
        Demand result = Demand.valueOf(demand_);
        return result == null ? Demand.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.example.protos.Message.Demand demand = 1;</code>
       * @param value The demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemand(Demand value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        demand_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.protos.Message.Demand demand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDemand() {
        
        demand_ = 0;
        onChanged();
        return this;
      }

      private int response_ = 0;
      /**
       * <code>.org.example.protos.Message.Response response = 2;</code>
       * @return The enum numeric value on the wire for response.
       */
      @Override public int getResponseValue() {
        return response_;
      }
      /**
       * <code>.org.example.protos.Message.Response response = 2;</code>
       * @param value The enum numeric value on the wire for response to set.
       * @return This builder for chaining.
       */
      public Builder setResponseValue(int value) {
        
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.protos.Message.Response response = 2;</code>
       * @return The response.
       */
      @Override
      public Response getResponse() {
        @SuppressWarnings("deprecation")
        Response result = Response.valueOf(response_);
        return result == null ? Response.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.example.protos.Message.Response response = 2;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(Response value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        response_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.protos.Message.Response response = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        
        response_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.protos.Message)
    }

    // @@protoc_insertion_point(class_scope:org.example.protos.Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protos_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protos_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\022\022org.example.protos\"\274\001\n\007" +
      "Message\0222\n\006demand\030\001 \001(\0162\".org.example.pr" +
      "otos.Message.Demand\0226\n\010response\030\002 \001(\0162$." +
      "org.example.protos.Message.Response\"\'\n\006D" +
      "emand\022\t\n\005CPCTY\020\000\022\010\n\004STRT\020\001\022\010\n\004STOP\020\002\"\034\n\010" +
      "Response\022\007\n\003YEP\020\000\022\007\n\003NOP\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_protos_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_protos_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protos_Message_descriptor,
        new String[] { "Demand", "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
