// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Subscriber.proto

package org.example.protos;

public final class SubscriberOuterClass {
  private SubscriberOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscriberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.protos.Subscriber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Abone ID'si
     * </pre>
     *
     * <code>int32 ID = 1;</code>
     * @return The iD.
     */
    int getID();

    /**
     * <pre>
     * Ad ve soyad
     * </pre>
     *
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    String getNameSurname();
    /**
     * <pre>
     * Ad ve soyad
     * </pre>
     *
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    com.google.protobuf.ByteString
        getNameSurnameBytes();

    /**
     * <pre>
     * Başlangıç tarihi
     * </pre>
     *
     * <code>int64 start_date = 3;</code>
     * @return The startDate.
     */
    long getStartDate();

    /**
     * <pre>
     * Son erişim tarihi
     * </pre>
     *
     * <code>int64 last_accessed = 4;</code>
     * @return The lastAccessed.
     */
    long getLastAccessed();

    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 5;</code>
     * @return A list containing the interests.
     */
    java.util.List<String>
        getInterestsList();
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 5;</code>
     * @return The count of interests.
     */
    int getInterestsCount();
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 5;</code>
     * @param index The index of the element to return.
     * @return The interests at the given index.
     */
    String getInterests(int index);
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interests at the given index.
     */
    com.google.protobuf.ByteString
        getInterestsBytes(int index);

    /**
     * <pre>
     * Online durumu
     * </pre>
     *
     * <code>bool isOnline = 6;</code>
     * @return The isOnline.
     */
    boolean getIsOnline();

    /**
     * <code>.org.example.protos.Subscriber.Demand demand = 7;</code>
     * @return The enum numeric value on the wire for demand.
     */
    int getDemandValue();
    /**
     * <code>.org.example.protos.Subscriber.Demand demand = 7;</code>
     * @return The demand.
     */
    Subscriber.Demand getDemand();
  }
  /**
   * Protobuf type {@code org.example.protos.Subscriber}
   */
  public static final class Subscriber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.protos.Subscriber)
      SubscriberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Subscriber.newBuilder() to construct.
    private Subscriber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subscriber() {
      nameSurname_ = "";
      interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      demand_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Subscriber();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SubscriberOuterClass.internal_static_org_example_protos_Subscriber_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SubscriberOuterClass.internal_static_org_example_protos_Subscriber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Subscriber.class, Builder.class);
    }

    /**
     * Protobuf enum {@code org.example.protos.Subscriber.Demand}
     */
    public enum Demand
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Abonelik talebi
       * </pre>
       *
       * <code>SUBS = 0;</code>
       */
      SUBS(0),
      /**
       * <pre>
       * Abonelik iptali
       * </pre>
       *
       * <code>DEL = 1;</code>
       */
      DEL(1),
      /**
       * <pre>
       * Güncelleme talebi
       * </pre>
       *
       * <code>UPDT = 2;</code>
       */
      UPDT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * Abonelik talebi
       * </pre>
       *
       * <code>SUBS = 0;</code>
       */
      public static final int SUBS_VALUE = 0;
      /**
       * <pre>
       * Abonelik iptali
       * </pre>
       *
       * <code>DEL = 1;</code>
       */
      public static final int DEL_VALUE = 1;
      /**
       * <pre>
       * Güncelleme talebi
       * </pre>
       *
       * <code>UPDT = 2;</code>
       */
      public static final int UPDT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Demand valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Demand forNumber(int value) {
        switch (value) {
          case 0: return SUBS;
          case 1: return DEL;
          case 2: return UPDT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Demand>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Demand> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Demand>() {
              public Demand findValueByNumber(int number) {
                return Demand.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Subscriber.getDescriptor().getEnumTypes().get(0);
      }

      private static final Demand[] VALUES = values();

      public static Demand valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Demand(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.example.protos.Subscriber.Demand)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int iD_;
    /**
     * <pre>
     * Abone ID'si
     * </pre>
     *
     * <code>int32 ID = 1;</code>
     * @return The iD.
     */
    @Override
    public int getID() {
      return iD_;
    }

    public static final int NAME_SURNAME_FIELD_NUMBER = 2;
    private volatile Object nameSurname_;
    /**
     * <pre>
     * Ad ve soyad
     * </pre>
     *
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    @Override
    public String getNameSurname() {
      Object ref = nameSurname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nameSurname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Ad ve soyad
     * </pre>
     *
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameSurnameBytes() {
      Object ref = nameSurname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nameSurname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_DATE_FIELD_NUMBER = 3;
    private long startDate_;
    /**
     * <pre>
     * Başlangıç tarihi
     * </pre>
     *
     * <code>int64 start_date = 3;</code>
     * @return The startDate.
     */
    @Override
    public long getStartDate() {
      return startDate_;
    }

    public static final int LAST_ACCESSED_FIELD_NUMBER = 4;
    private long lastAccessed_;
    /**
     * <pre>
     * Son erişim tarihi
     * </pre>
     *
     * <code>int64 last_accessed = 4;</code>
     * @return The lastAccessed.
     */
    @Override
    public long getLastAccessed() {
      return lastAccessed_;
    }

    public static final int INTERESTS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList interests_;
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 5;</code>
     * @return A list containing the interests.
     */
    public com.google.protobuf.ProtocolStringList
        getInterestsList() {
      return interests_;
    }
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 5;</code>
     * @return The count of interests.
     */
    public int getInterestsCount() {
      return interests_.size();
    }
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 5;</code>
     * @param index The index of the element to return.
     * @return The interests at the given index.
     */
    public String getInterests(int index) {
      return interests_.get(index);
    }
    /**
     * <pre>
     * İlgi alanları
     * </pre>
     *
     * <code>repeated string interests = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interests at the given index.
     */
    public com.google.protobuf.ByteString
        getInterestsBytes(int index) {
      return interests_.getByteString(index);
    }

    public static final int ISONLINE_FIELD_NUMBER = 6;
    private boolean isOnline_;
    /**
     * <pre>
     * Online durumu
     * </pre>
     *
     * <code>bool isOnline = 6;</code>
     * @return The isOnline.
     */
    @Override
    public boolean getIsOnline() {
      return isOnline_;
    }

    public static final int DEMAND_FIELD_NUMBER = 7;
    private int demand_;
    /**
     * <code>.org.example.protos.Subscriber.Demand demand = 7;</code>
     * @return The enum numeric value on the wire for demand.
     */
    @Override public int getDemandValue() {
      return demand_;
    }
    /**
     * <code>.org.example.protos.Subscriber.Demand demand = 7;</code>
     * @return The demand.
     */
    @Override public Demand getDemand() {
      @SuppressWarnings("deprecation")
      Demand result = Demand.valueOf(demand_);
      return result == null ? Demand.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0) {
        output.writeInt32(1, iD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nameSurname_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nameSurname_);
      }
      if (startDate_ != 0L) {
        output.writeInt64(3, startDate_);
      }
      if (lastAccessed_ != 0L) {
        output.writeInt64(4, lastAccessed_);
      }
      for (int i = 0; i < interests_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, interests_.getRaw(i));
      }
      if (isOnline_ != false) {
        output.writeBool(6, isOnline_);
      }
      if (demand_ != Demand.SUBS.getNumber()) {
        output.writeEnum(7, demand_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nameSurname_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nameSurname_);
      }
      if (startDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startDate_);
      }
      if (lastAccessed_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastAccessed_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < interests_.size(); i++) {
          dataSize += computeStringSizeNoTag(interests_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInterestsList().size();
      }
      if (isOnline_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isOnline_);
      }
      if (demand_ != Demand.SUBS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, demand_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Subscriber)) {
        return super.equals(obj);
      }
      Subscriber other = (Subscriber) obj;

      if (getID()
          != other.getID()) return false;
      if (!getNameSurname()
          .equals(other.getNameSurname())) return false;
      if (getStartDate()
          != other.getStartDate()) return false;
      if (getLastAccessed()
          != other.getLastAccessed()) return false;
      if (!getInterestsList()
          .equals(other.getInterestsList())) return false;
      if (getIsOnline()
          != other.getIsOnline()) return false;
      if (demand_ != other.demand_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      hash = (37 * hash) + NAME_SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNameSurname().hashCode();
      hash = (37 * hash) + START_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartDate());
      hash = (37 * hash) + LAST_ACCESSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastAccessed());
      if (getInterestsCount() > 0) {
        hash = (37 * hash) + INTERESTS_FIELD_NUMBER;
        hash = (53 * hash) + getInterestsList().hashCode();
      }
      hash = (37 * hash) + ISONLINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOnline());
      hash = (37 * hash) + DEMAND_FIELD_NUMBER;
      hash = (53 * hash) + demand_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Subscriber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Subscriber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Subscriber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Subscriber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Subscriber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Subscriber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Subscriber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Subscriber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Subscriber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Subscriber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Subscriber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.protos.Subscriber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.protos.Subscriber)
        SubscriberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SubscriberOuterClass.internal_static_org_example_protos_Subscriber_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SubscriberOuterClass.internal_static_org_example_protos_Subscriber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Subscriber.class, Builder.class);
      }

      // Construct using org.example.protos.SubscriberOuterClass.Subscriber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        iD_ = 0;

        nameSurname_ = "";

        startDate_ = 0L;

        lastAccessed_ = 0L;

        interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        isOnline_ = false;

        demand_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SubscriberOuterClass.internal_static_org_example_protos_Subscriber_descriptor;
      }

      @Override
      public Subscriber getDefaultInstanceForType() {
        return Subscriber.getDefaultInstance();
      }

      @Override
      public Subscriber build() {
        Subscriber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Subscriber buildPartial() {
        Subscriber result = new Subscriber(this);
        int from_bitField0_ = bitField0_;
        result.iD_ = iD_;
        result.nameSurname_ = nameSurname_;
        result.startDate_ = startDate_;
        result.lastAccessed_ = lastAccessed_;
        if (((bitField0_ & 0x00000001) != 0)) {
          interests_ = interests_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.interests_ = interests_;
        result.isOnline_ = isOnline_;
        result.demand_ = demand_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Subscriber) {
          return mergeFrom((Subscriber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Subscriber other) {
        if (other == Subscriber.getDefaultInstance()) return this;
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (!other.getNameSurname().isEmpty()) {
          nameSurname_ = other.nameSurname_;
          onChanged();
        }
        if (other.getStartDate() != 0L) {
          setStartDate(other.getStartDate());
        }
        if (other.getLastAccessed() != 0L) {
          setLastAccessed(other.getLastAccessed());
        }
        if (!other.interests_.isEmpty()) {
          if (interests_.isEmpty()) {
            interests_ = other.interests_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInterestsIsMutable();
            interests_.addAll(other.interests_);
          }
          onChanged();
        }
        if (other.getIsOnline() != false) {
          setIsOnline(other.getIsOnline());
        }
        if (other.demand_ != 0) {
          setDemandValue(other.getDemandValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                iD_ = input.readInt32();

                break;
              } // case 8
              case 18: {
                nameSurname_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 24: {
                startDate_ = input.readInt64();

                break;
              } // case 24
              case 32: {
                lastAccessed_ = input.readInt64();

                break;
              } // case 32
              case 42: {
                String s = input.readStringRequireUtf8();
                ensureInterestsIsMutable();
                interests_.add(s);
                break;
              } // case 42
              case 48: {
                isOnline_ = input.readBool();

                break;
              } // case 48
              case 56: {
                demand_ = input.readEnum();

                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int iD_ ;
      /**
       * <pre>
       * Abone ID'si
       * </pre>
       *
       * <code>int32 ID = 1;</code>
       * @return The iD.
       */
      @Override
      public int getID() {
        return iD_;
      }
      /**
       * <pre>
       * Abone ID'si
       * </pre>
       *
       * <code>int32 ID = 1;</code>
       * @param value The iD to set.
       * @return This builder for chaining.
       */
      public Builder setID(int value) {
        
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Abone ID'si
       * </pre>
       *
       * <code>int32 ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearID() {
        
        iD_ = 0;
        onChanged();
        return this;
      }

      private Object nameSurname_ = "";
      /**
       * <pre>
       * Ad ve soyad
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @return The nameSurname.
       */
      public String getNameSurname() {
        Object ref = nameSurname_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nameSurname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Ad ve soyad
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @return The bytes for nameSurname.
       */
      public com.google.protobuf.ByteString
          getNameSurnameBytes() {
        Object ref = nameSurname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nameSurname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Ad ve soyad
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @param value The nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurname(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nameSurname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ad ve soyad
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNameSurname() {
        
        nameSurname_ = getDefaultInstance().getNameSurname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ad ve soyad
       * </pre>
       *
       * <code>string name_surname = 2;</code>
       * @param value The bytes for nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nameSurname_ = value;
        onChanged();
        return this;
      }

      private long startDate_ ;
      /**
       * <pre>
       * Başlangıç tarihi
       * </pre>
       *
       * <code>int64 start_date = 3;</code>
       * @return The startDate.
       */
      @Override
      public long getStartDate() {
        return startDate_;
      }
      /**
       * <pre>
       * Başlangıç tarihi
       * </pre>
       *
       * <code>int64 start_date = 3;</code>
       * @param value The startDate to set.
       * @return This builder for chaining.
       */
      public Builder setStartDate(long value) {
        
        startDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Başlangıç tarihi
       * </pre>
       *
       * <code>int64 start_date = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartDate() {
        
        startDate_ = 0L;
        onChanged();
        return this;
      }

      private long lastAccessed_ ;
      /**
       * <pre>
       * Son erişim tarihi
       * </pre>
       *
       * <code>int64 last_accessed = 4;</code>
       * @return The lastAccessed.
       */
      @Override
      public long getLastAccessed() {
        return lastAccessed_;
      }
      /**
       * <pre>
       * Son erişim tarihi
       * </pre>
       *
       * <code>int64 last_accessed = 4;</code>
       * @param value The lastAccessed to set.
       * @return This builder for chaining.
       */
      public Builder setLastAccessed(long value) {
        
        lastAccessed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Son erişim tarihi
       * </pre>
       *
       * <code>int64 last_accessed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastAccessed() {
        
        lastAccessed_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInterestsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          interests_ = new com.google.protobuf.LazyStringArrayList(interests_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 5;</code>
       * @return A list containing the interests.
       */
      public com.google.protobuf.ProtocolStringList
          getInterestsList() {
        return interests_.getUnmodifiableView();
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 5;</code>
       * @return The count of interests.
       */
      public int getInterestsCount() {
        return interests_.size();
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 5;</code>
       * @param index The index of the element to return.
       * @return The interests at the given index.
       */
      public String getInterests(int index) {
        return interests_.get(index);
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the interests at the given index.
       */
      public com.google.protobuf.ByteString
          getInterestsBytes(int index) {
        return interests_.getByteString(index);
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 5;</code>
       * @param index The index to set the value at.
       * @param value The interests to set.
       * @return This builder for chaining.
       */
      public Builder setInterests(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInterestsIsMutable();
        interests_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 5;</code>
       * @param value The interests to add.
       * @return This builder for chaining.
       */
      public Builder addInterests(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInterestsIsMutable();
        interests_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 5;</code>
       * @param values The interests to add.
       * @return This builder for chaining.
       */
      public Builder addAllInterests(
          Iterable<String> values) {
        ensureInterestsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, interests_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterests() {
        interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * İlgi alanları
       * </pre>
       *
       * <code>repeated string interests = 5;</code>
       * @param value The bytes of the interests to add.
       * @return This builder for chaining.
       */
      public Builder addInterestsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInterestsIsMutable();
        interests_.add(value);
        onChanged();
        return this;
      }

      private boolean isOnline_ ;
      /**
       * <pre>
       * Online durumu
       * </pre>
       *
       * <code>bool isOnline = 6;</code>
       * @return The isOnline.
       */
      @Override
      public boolean getIsOnline() {
        return isOnline_;
      }
      /**
       * <pre>
       * Online durumu
       * </pre>
       *
       * <code>bool isOnline = 6;</code>
       * @param value The isOnline to set.
       * @return This builder for chaining.
       */
      public Builder setIsOnline(boolean value) {
        
        isOnline_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Online durumu
       * </pre>
       *
       * <code>bool isOnline = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOnline() {
        
        isOnline_ = false;
        onChanged();
        return this;
      }

      private int demand_ = 0;
      /**
       * <code>.org.example.protos.Subscriber.Demand demand = 7;</code>
       * @return The enum numeric value on the wire for demand.
       */
      @Override public int getDemandValue() {
        return demand_;
      }
      /**
       * <code>.org.example.protos.Subscriber.Demand demand = 7;</code>
       * @param value The enum numeric value on the wire for demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemandValue(int value) {
        
        demand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.protos.Subscriber.Demand demand = 7;</code>
       * @return The demand.
       */
      @Override
      public Demand getDemand() {
        @SuppressWarnings("deprecation")
        Demand result = Demand.valueOf(demand_);
        return result == null ? Demand.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.example.protos.Subscriber.Demand demand = 7;</code>
       * @param value The demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemand(Demand value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        demand_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.protos.Subscriber.Demand demand = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDemand() {
        
        demand_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.protos.Subscriber)
    }

    // @@protoc_insertion_point(class_scope:org.example.protos.Subscriber)
    private static final Subscriber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Subscriber();
    }

    public static Subscriber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscriber>
        PARSER = new com.google.protobuf.AbstractParser<Subscriber>() {
      @Override
      public Subscriber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Subscriber> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Subscriber> getParserForType() {
      return PARSER;
    }

    @Override
    public Subscriber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protos_Subscriber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protos_Subscriber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020Subscriber.proto\022\022org.example.protos\"\334" +
      "\001\n\nSubscriber\022\n\n\002ID\030\001 \001(\005\022\024\n\014name_surnam" +
      "e\030\002 \001(\t\022\022\n\nstart_date\030\003 \001(\003\022\025\n\rlast_acce" +
      "ssed\030\004 \001(\003\022\021\n\tinterests\030\005 \003(\t\022\020\n\010isOnlin" +
      "e\030\006 \001(\010\0225\n\006demand\030\007 \001(\0162%.org.example.pr" +
      "otos.Subscriber.Demand\"%\n\006Demand\022\010\n\004SUBS" +
      "\020\000\022\007\n\003DEL\020\001\022\010\n\004UPDT\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_protos_Subscriber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_protos_Subscriber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protos_Subscriber_descriptor,
        new String[] { "ID", "NameSurname", "StartDate", "LastAccessed", "Interests", "IsOnline", "Demand", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
